---
- hosts: all
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Update hostname
      hostname:
        name: "{{ ansible_hostname }}"
    - name: Update /etc/hosts file
      template:
        src:    templates/etc_hosts.j2
        dest:   /etc/hosts
        owner:  root
        group:  root
        mode:   0644
    - name: Ensure proxies are set for Consul
      template:
        src:    templates/etc_profile_d_proxy_sh.j2
        dest:   /etc/profile.d/proxy.sh
        owner:  root
        group:  root
        mode:   0644
    - name: Install required packages
      package:
        name:   "{{ item }}"
        state:  present
      with_items:
        - "unzip"

- hosts: consul
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Download latest Consul binary
      unarchive:
        src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
        owner: root
        group: root
        creates: /usr/bin/consul
    - name: Create Consul group
      group:
        name: consul
    - name: Create Consul user
      user:
        group: consul
        home: /var/lib/consul
        name: consul
        shell: /sbin/nologin
    - name: Create Consul directories
      file:
        path: "{{ item }}"
        state: directory
        owner: consul
        group: consul
      with_items:
        - /etc/consul.d
        - /var/lib/consul
    - name: Create Consul systemd configuration
      template:
        src: consul.service.j2
        dest: /usr/lib/systemd/system/consul.service
        owner: root
        group: root
        mode: 0644
      notify: Restart Consul service
    - name: Create Consul service configuration
      template:
        src: consul.json.j2
        dest: /etc/consul.d/consul.json
        owner: root
        group: root
        mode: 0644
      notify: Restart Consul service
    - name: Enable Consul service
      service:
        name: consul
        state: started
        enabled: yes
  handlers:
    - name: Restart Consul service
      service:
        name: consul
        daemon_reload: yes
        state: restarted

- hosts: consul_client
  vars_files:
    - external_variables.yaml
  tasks:
    - name: Download latest Consul Template binary
      unarchive:
        src: https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
        owner: root
        group: root
        creates: /usr/bin/consul
    - name: Create Consul Template directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - /etc/consul-template.d
    - name: Create Consul Template systemd configuration
      template:
        src: consul-template.service.j2
        dest: /usr/lib/systemd/system/consul-template.service
        owner: root
        group: root
        mode: 0644
